#!/bin/bash

title="Appear.in Install"
size="120000" # 120MB
backgroundPictureName="dmg_background.png"
applicationName="Appear.in"
volumePath="/Volumes/${title}"
finalDMGName="build/Appear.in-Install.dmg"
source="build/Appear.in-darwin-x64"

hdiutil create -srcfolder "${source}" -volname "${title}" -fs HFS+ \
  -fsargs "-c c=64,a=16,e=16" -format UDRW -size ${size}k build/pack.temp.dmg

sleep 1

device=$(hdiutil attach -readwrite -noverify -noautoopen "build/pack.temp.dmg" | \
  egrep '^/dev/' | sed 1q | awk '{print $1}')

mkdir "${volumePath}/.background"
cp "${backgroundPictureName}" "${volumePath}/.background"

osascript <<EOF
tell application "Finder"
  tell disk "${title}"
    open
    set current view of container window to icon view
    set toolbar visible of container window to false
    set statusbar visible of container window to false
    set the bounds of container window to {400, 100, 885, 450}
    set theViewOptions to the icon view options of container window
    set arrangement of theViewOptions to not arranged
    set icon size of theViewOptions to 72
    set background picture of theViewOptions to file ".background:${backgroundPictureName}"
    make new alias file at container window to POSIX file "/Applications" with properties {name:"Applications"}
    set position of item "LICENSE" of container window to {100, 245}
    set position of item "LICENSES.chromium.html" of container window to {235, 245}
    set position of item "VERSION" of container window to {375, 245}
    set position of item "${applicationName}" of container window to {100, 100}
    set position of item "Applications" of container window to {375, 100}
    close
    open
    update without registering applications
    delay 5
    close
  end tell
end tell
EOF

chmod -Rf go-w "${volumePath}"
sync
sleep 1

hdiutil detach ${device}
hdiutil convert "build/pack.temp.dmg" -format UDZO -imagekey zlib-level=9 -o "${finalDMGName}"
