#!/bin/bash

mkdir -p build/Logo.iconset
sips -z 16 16     appearin-logo.png --out build/Logo.iconset/icon_16x16.png
sips -z 32 32     appearin-logo.png --out build/Logo.iconset/icon_16x16@2x.png
sips -z 32 32     appearin-logo.png --out build/Logo.iconset/icon_32x32.png
sips -z 64 64     appearin-logo.png --out build/Logo.iconset/icon_32x32@2x.png
sips -z 128 128   appearin-logo.png --out build/Logo.iconset/icon_128x128.png
sips -z 256 256   appearin-logo.png --out build/Logo.iconset/icon_128x128@2x.png
sips -z 256 256   appearin-logo.png --out build/Logo.iconset/icon_256x256.png
sips -z 512 512   appearin-logo.png --out build/Logo.iconset/icon_256x256@2x.png
sips -z 512 512   appearin-logo.png --out build/Logo.iconset/icon_512x512.png
cp appearin-logo.png build/Logo.iconset/icon_512x512@2x.png
iconutil -c icns --output build/Logo.icns build/Logo.iconset
